[package]
name = "policy-server"
version = "0.1.7"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-stream = "0.3.0"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", branch = "opa" }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.1.13" }
kubewarden-policy-sdk = "0.2.4"
clap = "2.33.3"
futures-util = "0.3.12"
kube = "0.51.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
hyper-tls = "0.5.0"
hyper = { version = "0.14", features = ["full"] }
num_cpus = "1.13.0"
openssl = "0.10.32"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.15"
tokio-native-tls = "0.3.0"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version= "0.2", features = ["fmt"] }
tracing-futures = "0.2"
# TODO tracing-opentelemetry: once a new release is tagged check if we can update all the other telemetry crates
tracing-opentelemetry = "0.13.0"
# opentelemetry-jaeger: we have to stick with 0.13 because it's the last release that builds against opentelemetry 0.14
opentelemetry-jaeger = { version = "0.13.0", features = ["collector_client", "reqwest_collector_client"] }
# opentelemetry: we have to stick with 0.14 because tracing-opentelemetry is built against it
opentelemetry = { version = "0.14", default-features = false, features = ["trace", "rt-tokio"] }
# opentelemetry-otlp: we have to stick with 0.7.0 because it's the last version building against opentelemetry 0.14
opentelemetry-otlp = "0.7.0"