[package]
name = "policy-server"
version = "1.0.0-rc2"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>",
  "Víctor Cuadrado Juan <vcuadradojuan@suse.de>"
]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-stream = "0.3.3"
itertools = "0.10.3"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.3.7" }
lazy_static = "1.4.0"
clap = { version = "3.2.5", features = [ "cargo", "env" ] }
futures-util = "0.3.21"
k8s-openapi = { version = "0.15.0", default-features = false, features = ["v1_24"] }
hyper = { version = "0.14", features = ["full"] }
num_cpus = "1.13.1"
opentelemetry = { version = "0.17", default-features = false, features = ["metrics", "trace", "rt-tokio", "serialize"] }
opentelemetry-otlp = { version = "0.10.0", features = ["metrics", "tonic"] }
rustls = "0.20.6"
rustls-pemfile = "1.0.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.24"
tokio = { version = "^1", features = ["full"] }
tokio-rustls = "0.23.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
tracing-futures = "0.2"
tracing-opentelemetry = "0.17.3"

[dev-dependencies]
tempfile = "3.3.0"

[patch.crates-io]
# Forcing base64ct to version 1.1.1 given that version 1.2.0 has been
# bumped to use Rust 2021 edition. When we see is time, we can bump as
# well, but for now, pin to 1.1.1 that is bound to edition 2018.
base64ct = { git = "https://github.com/RustCrypto/formats.git", tag = "base64ct/v1.1.1" }
