name: Build container image every change.

on:
  push:
    branches:
      - main
    tags:
      - 'v*'


jobs:
  build:
    name: Build
    uses: jvanz/policy-server/.github/workflows/container-image.yml@main
    with:
      push-image: true
