name: Security audit cron job
on:
  schedule:
    - cron: '0 0 * * *'

# Declare default permissions as read only.
permissions: read-all

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
