name: Update rust-toolchain

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1" # 3:30 on Monday

jobs:
  update-rust-toolchain:
    name: Update Rust toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@719e3592d124cbf826da704cbe557e1221dd4bba # v2.94.0

      - name: Update rust version inside of rust-toolchain file
        id: update_rust_toolchain
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: |-
          updatecli apply --config ./updatecli/updatecli.d/update-rust-toolchain.yaml \
                    --values updatecli/values.yaml
